#
#    BAMobCoins
#
####################################################
# %PLAYER% - Will be replaced with the player who clicked the item (Buying from the shop)
# [MESSAGE] - Will send a message to the player
# [BROADCAST] - Will broadcast a message to the whole server
######################################################
Options:
  Prefix: '&7[&6BAMobCoins&7]'
  BroadcastPrefix: '&7[&b&lAnnouncment&7]'
  Title: '&7[&6BAMobCoins - Shop&7]'
  CurrencyNameSingle: '&bMobCoin'
  CurrencyNamePlural: '&bMobCoins'
  BorderItem:
    Material: STAINED_GLASS_PANE
    Meta: 10
    Name: " "
Coin:
  Item: DOUBLE_PLANT
  Meta: 0
  Name: '&6&lMob Coin'
  Lore:
  - '&7Right click to deposit!'
Shop:
  DevRank: #<-- This value MUST be unique
    Item: CAKE
    Meta: 0
    Amount: 1
    Slot: 14
    DisplayName: '&b&lDev Rank!'
    Price: 100
    Lore: ''
    Commands:
    - 'pex user %PLAYER% group add Dev'
  MobCoinRank:
    Item: CAKE
    Meta: 0
    Amount: 1
    Slot: 13
    DisplayName: '&b&lBAMobCoins Rank!'
    Price: 100
    Lore: ''
    Commands:
    - 'pex user %PLAYER% group add BAMobCoins'
  PlayerRank:
    Item: CAKE
    Meta: 0
    Amount: 1
    Slot: 12
    DisplayName: '&b&lPlayer Rank!'
    Price: 100
    Lore: ''
    Commands:
    - 'pex user %PLAYER% group add Player'
  20kEco:
    Item: GOLD_INGOT
    Meta: 0
    Amount: 1
    Slot: 21
    DisplayName: '&b&l20k!'
    Price: 100
    Lore: ''
    Commands:
    - 'eco give %PLAYER% 20000'
  50kEco:
    Item: GOLD_INGOT
    Meta: 0
    Amount: 1
    Slot: 22
    DisplayName: '&b&l50k!'
    Price: 100
    Lore: ''
    Commands:
    - 'eco give %PLAYER% 50000'
  100kEco:
    Item: GOLD_INGOT
    Meta: 0
    Amount: 1
    Slot: 23
    DisplayName: '&b&l100k!'
    Price: 100
    Lore: ''
    Commands:
    - 'eco give %PLAYER% 100000'
  MythicalCrate:
    Item: TRIPWIRE_HOOK
    Meta: 0
    Amount: 1
    Slot: 30
    DisplayName: '&b&lMythical Crate Key!'
    Price: 100
    Lore: ''
    Commands:
    - 'Put crate command here'
  EnchantCrate:
    Item: TRIPWIRE_HOOK
    Meta: 0
    Amount: 1
    Slot: 31
    DisplayName: '&b&lCustom Enchant Crate Key!'
    Price: 100
    Lore: ''
    Commands:
    - 'Put crate command here'
  LegendaryCrate:
    Item: TRIPWIRE_HOOK
    Meta: 0
    Amount: 1
    Slot: 32
    DisplayName: '&b&lLegendery Crate Key!'
    Price: 100
    Lore: ''
    Commands:
    - 'Put crate command here'
  FlyCommand:
    Item: FEATHER
    Meta: 0
    Amount: 1
    Slot: 39
    DisplayName: '&b&lFly!'
    Price: 100
    Lore: ''
    Commands:
    - 'pex user %PLAYER% add essentials.fly'
    - 'pex user %PLAYER% add essentials.fly.safelogin'
  ConfidenceBoost:
    Item: GOLD_INGOT
    Meta: 0
    Amount: 1
    Slot: 40
    DisplayName: '&d&lA confidence boost'
    Price: 100
    Lore: ''
    Commands:
    # Take notice to the double single quote. This will allow it to be displayed.
    - '[MESSAGE] You''re doing great setting up this config'
  Nothing:
    Item: DRAGON_EGG
    Meta: 0
    Amount: 1
    Slot: 41
    DisplayName: '&b&lNothing!'
    Price: 100
    Lore:
    - '&bThis is the best purchase'
    - '&byou will &d&lEVER &bmake.'
    Commands:
    - '[BROADCAST] &d%PLAYER% &fhas bought nothing!'
DropChances:
  # Leave value as -1 for them to not be active
  # The value entered is the percent for the drop.
  # eg 
  #   BAT: 20
  # Means theres a 20% chance a bat will give a coin when killed.
  # Passive Mobs
  BAT: -1
  SQUID: -1
  RABBIT: -1
  CHICKEN: -1
  PIG: -1
  SHEEP: -1
  COW: -1
  MUSHROOMCOW: -1
  SNOWMAN: -1
  OCELOT: -1
  HORSE: -1
  # Hostile Mobs
  ZOMBIE: -1
  SKELETON: -1
  SPIDER: -1
  CAVESPIDER: -1
  CREEPER: -1
  ENDERMAN: -1
  BLAZE: -1
  WITCH: -1
  SILVERFISH: -1
  MAGMACUBE: -1
  ENDERMITE: -1
  GUARDIAN: -1
  GHAST: -1
  SLIME: -1
  GIANT: -1
  WITHER: -1
  ENDERDRAGON: -1
  # Neutral Mobs
  VILLAGER: -1
  IRONGOLEM: -1
  PIGMAN: -1
  WOLF: -1
  # Can even set it up for players
  PLAYER: -1