#
#    MobCoins by Brody
#    github: https://github.com/Broanater/MobCoins
#
Options:
  Prefix: '&7[&6BAMobCoins&7]'
  Title: '&7[&6BAMobCoins - Shop&7]'
Shop:
  '0':
    Item: CAKE
    Meta: 0
    Amount: 1
    Slot: 14
    DisplayName: '&b&lKingRank!'
    Price: 100
    Lore: ''
    Commands:
    - pex user %player% group add BrodyRank
  '1':
    Item: CAKE
    Meta: 0
    Amount: 1
    Slot: 13
    DisplayName: '&b&lGuardianRank!'
    Price: 100
    Lore: ''
    Commands:
    - pex user %player% group add Mobcoins
  '2':
    Item: CAKE
    Meta: 0
    Amount: 1
    Slot: 12
    DisplayName: '&b&lAvengerRank!'
    Price: 100
    Lore: ''
    Commands:
    - pex user %player% group add Avenger
  '3':
    Item: TRIPWIRE_HOOK
    Meta: 0
    Amount: 1
    Slot: 30
    DisplayName: '&b&lMythical Crate Key!'
    Price: 100
    Lore: ''
    Commands:
    - Put crate command here
  '4':
    Item: TRIPWIRE_HOOK
    Meta: 0
    Amount: 1
    Slot: 31
    DisplayName: '&b&lCustom Enchant Crate Key!'
    Price: 100
    Lore: ''
    Commands:
    - Put crate command here
  '5':
    Item: TRIPWIRE_HOOK
    Meta: 0
    Amount: 1
    Slot: 32
    DisplayName: '&b&lLegendery Crate Key!'
    Price: 100
    Lore: ''
    Commands:
    - Put crate command here
  '6':
    Item: FEATHER
    Meta: 0
    Amount: 1
    Slot: 40
    DisplayName: '&b&lFly!'
    Price: 100
    Lore: ''
    Commands:
    - pex user %player% add essentials.fly
    - pex user %player% add essentials.fly.safelogin
  '7':
    Item: GOLD_INGOT
    Meta: 0
    Amount: 1
    Slot: 21
    DisplayName: '&b&l20k!'
    Price: 100
    Lore: ''
    Commands:
    - eco give %player% 20000
  '8':
    Item: GOLD_INGOT
    Meta: 0
    Amount: 1
    Slot: 22
    DisplayName: '&b&l50k!'
    Price: 100
    Lore: ''
    Commands:
    - eco give %player% 50000
  '9':
    Item: GOLD_INGOT
    Meta: 0
    Amount: 1
    Slot: 23
    DisplayName: '&b&l100k!'
    Price: 100
    Lore: ''
    Commands:
    - eco give %player% 100000
DropChances:
  #Leave value as -1 for them to not be active
  #Passive Mobs
  BAT: -1
  SQUID: -1
  RABBIT: -1
  CHICKEN: -1
  PIG: -1
  SHEEP: -1
  COW: -1
  MUSHROOMCOW: -1
  SNOWMAN: -1
  OCELOT: -1
  HORSE: -1
  #Hostile Mobs
  ZOMBIE: -1
  SKELETON: -1
  SPIDER: -1
  CAVESPIDER: -1
  CREEPER: -1
  ENDERMAN: -1
  BLAZE: -1
  WITCH: -1
  SILVERFISH: -1
  MAGMACUBE: -1
  ENDERMITE: -1
  GUARDIAN: -1
  GHAST: -1
  SLIME: -1
  GIANT: -1
  WITHER: -1
  ENDERDRAGON: -1
  #Neutral Mobs
  VILLAGER: -1
  IRONGOLEM: -1
  PIGMAN: -1
  WOLF: -1
  #Can even set it up for players
  PLAYER: -1